# 代理设置，如果无需使用代理请用两个单引号 '' 表示留空
Proxy:
  Host: ''
  Port: ''

# 找到 www.pixiv.net 的 cookie 中 PHPSESSID 键的值填入此项
Cookie: 'YOUR-COOKIE-HERE'

# 爬虫程序运行时, 将使用此页面作为开始页面
# 爬虫程序会在运行时，不断写入此项，以便于下次运行时接着爬取
StartPage: 'PIXIV-URL-HERE'

#图片文件的储存路径, %HERE%会被程序自动替换成jar文件所在的文件夹
ImgSavePath: '%HERE%/Crawled'
